language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t abhishek/docker-react -f Dockerfile.dev .

script:
  - docker run abhishek/docker-react npm run test -- --coverage
